#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d postgres <<-EOSQL
    CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASSWORD';
    CREATE DATABASE "$AUTH_DB_NAME" OWNER $AUTH_DB_USER;

    CREATE USER $CATALOG_DB_USER WITH PASSWORD '$CATALOG_DB_PASSWORD';
    CREATE DATABASE "$CATALOG_DB_NAME" OWNER $CATALOG_DB_USER;
EOSQL
